name: Django Project Test

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Compose
      run: docker compose -f docker-compose-stage.yml up --build
    - name: Run Test
      run: docker compose exec -T backend sh -c "flake8 && pytest ."
